### ISSUE TITLE
Calendar folder permission

### ISSUE THREAD

**Issue by YujiShen** [ndw/org-mac-iCal#1]
Do you enable SIP on your Mac? I have to enable SIP to make it work. Otherwise, it will report error because it can not open Calendar folder, even though I give 777 permissions to all Calendar files (when SIP is disabled). Is this normal? It seems Calendar folder is not under the protection of SIP.

**Comment by ndw** [comment]
You have to give the terminal access to all files: System Preferences -> Security & Privacy -> Privacy -> Full Disk Access

**Comment by zinoff** [comment]
I have the same issue even after having given access to all files to Terminal.
I started emacs from terminal and it didn't throw an error, however the calendar stays at 0 bytes.

**Comment by ndw** [comment]
You may have to give Emacs access to your whole disk as well.

**Comment by zinoff** [comment]
I had done that before posting. To be honest it worked at some point in May 2020 without giving additional permission.  I have now cooked up a temporary contraption with iCalbuddy and sed.

**Comment by cerkut** [comment]
Giving terminal and emacs Full Disk access solves the permissions for me.

**Comment by YujiShen** [comment]
Thanks for help! I changed to use Google Calendar with org-gcal now. Have not tried org-mac-iCal again. But I think the Full Disk access should work.
